language: python
python:
  - 3.9
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libhttprequests --cov=libhttprequests
after_success:
  - codecov